#!/usr/bin/env python
from Matrix import Matrix, IdentityMatrix
from Tuple4 import Tuple4

print("Inverting the identity matrix")

id = IdentityMatrix(4)

print("ID matrix:")
print(id)
print("Inverted:")
print(id.inverse())

m = Matrix([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, -8, 7, -6],
            [5, -4, 3, -2]])

print("Matrix multiplied by its inverse")
print(m)
print(m.determinant())
print(m * m.inverse())

print("Inverse of transpose vs transpose of inverse")
print(m.transpose().inverse())
print(m.inverse().transpose())
print(m.inverse().transpose() == m.transpose().inverse())

t = Tuple4(1, -2, 3, 0)
print(id * t)
id[0][0] = 4
print(id * t)
